#!/bin/bash

##################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like ##SBATCH
##################

#SBATCH --partition main			### specify partition name where to run a job. debug: 2 hours limit; short: 7 days limit
#SBATCH --time 6-23:59:59			### limit the time of job running, partition limit can override this. Format: D-H:MM:SS
#SBATCH --job-name ICTS_CPU			### name of the job
#SBATCH --output test_cpu_job-%J.out			### output log for running job - %J for job number
##SBATCH --mail-user=lioryasu@post.bgu.ac.il	### user email for sending job status
##SBATCH --mail-type=ALL			### conditions when to send the email. ALL,BEGIN,END,FAIL, REQUEU, NONE


#SBATCH --mem=64G                              ### amount of RAM memory
#SBATCH --cpus-per-task=20                      ### number of CPU cores

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n"

### Start you code below ####
module load anaconda				### load anaconda module (must present when working with conda environments)
source activate stargan				### activating environment, environment must be configured before running the job
python runner_new.py			### execute jupyter lab command – replace with your own command
						### (e.g. “srun --mem=24G python my.py my_arg”.
						### You may use multiple srun lines, they are the job steps.
						### --mem - memory to allocate: use 24G x number for each allocated GPUs (24G * nGPU)

